### ISSUE TITLE
Add screenshot(s) to the quickstart

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible-docs#1]
I think we're at the point where the interface is far enough along that the screenshot(s) I'm referencing can be made. I think it would be helpful to have visual cues in addition to the descriptions you've provided for how to navigate the site.

For context, I'm referencing this section specifically.

<img width="908" alt="CleanShot 2023-03-13 at 10 01 32@2x" src="https://user-images.githubusercontent.com/37086973/224724376-3440195b-cb07-4932-9ae9-64ddd550e1b6.png">

**Comment by 0xTranqui** [comment]
adding on to this I think pictures throughout the entire "Getting Started" section would be really valuable. Obviously need to wait to add those until the front end is more complete -- so just throwing in a +1 to this issue in the meantime

**Comment by Valcoholics** [comment]
The deploy part of the quickstart in my opinion doesn't need screenshots anymore and depending on the final color of the app the photos will need to be redone again.

**Comment by salieflewis** [comment]
Ok, closing this.
