### ISSUE TITLE
Bug: remove /examples from the navigation bar when on the index/home page

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible-docs#17]
When you're on the index page, `/examples` still shows up, not sure why this is the case, maybe you can figure this out @Valcoholics

**Comment by salieflewis** [comment]
This seemed to go away, maybe I was on the wrong link.

**Comment by Valcoholics** [comment]
It's janky, i fix it by adding the meta.json files to each folder, it's remembering old deploys for some reason, will open the issue to the nextra team as well
