### ISSUE TITLE
Feat: Make it more obvious where to find documentation

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible-docs#19]
tldr its not clear/obvious that you need to click on the "Documentation" tab in the header. was looking at this for a while before figuring it out. not sure what the fix (maybe an extra in line link to documnetation in the body text of the landing?... but yea

<img width="1512" alt="Screen Shot 2023-03-27 at 5 51 08 PM" src="https://user-images.githubusercontent.com/93691906/228075164-0b128ff5-5809-4780-88ce-1b033d644f4f.png">

**Comment by Valcoholics** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/91724117/228075671-2487e986-d347-48eb-9fb2-86e1b945fa79.png)

**Comment by 0xTranqui** [comment]
yea i think that could be perf!
