### ISSUE TITLE
environment variable stuff

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible-docs#2]
Two things:

1. highlighted text repeats "NEXT_DAO_ADDRESS" instead of "NEXT_ALCHEMY_KEY"

<img width="647" alt="Screen Shot 2023-03-14 at 10 10 16 AM" src="https://user-images.githubusercontent.com/93691906/225027737-6feb0448-bc8e-489f-8749-89481e00ad4c.png">

2. After recent convos with @salieflewis I believe we're gonna want to be able to throw a chainID in the environment variable flow to support testnet

**Comment by salieflewis** [comment]
This is what the env.example currently looks like sans the PA stuff.

```
NEXT_PUBLIC_SITE_TITLE='Public Assembly'
NEXT_PUBLIC_APP_ID='public-assembly'
NEXT_PUBLIC_SITE_DESCRIPTION="create what's missing"
NEXT_PUBLIC_TWITTER_HANDLE='pblcasmbly'
NEXT_PUBLIC_WEBSITE_URL='https://public---assembly.com'
NEXT_PUBLIC_CHAIN_ID=''
NEXT_PUBLIC_ALCHEMY_KEY=''
NEXT_PUBLIC_TOKEN_ADDRESS=''
NEXT_PUBLIC_PLATFORM_INDEX=''
NEXT_PUBLIC_WEB3STORAGE_TOKEN=''
NEXT_PUBLIC_REGISTRY_CONTRACT=''
```

One thing that might change is that the registry contract may be hardcoded in. Also, people can submit either Alchemy or Infura keys, not sure just yet how we'll best communicate that.

**Comment by 0xTranqui** [comment]
I think registry contract can/should def be hardcoded in. semi related -- will ppl have the option to override the inputs into the theming variables? I imagine some ppl may want to just hardcode in theming variables and not deal with the whole IPFS thing

for the alchemy/infura bit, maybe just call it RPC Provider Key?

also cross posting this [issue](https://github.com/public-assembly/dao-utils/issues/51) I added to dao-utils this morning, should prob add an (optional) zora api key slot, which will be necessary for ppl with platforms that get high levels of traction

**Comment by Valcoholics** [comment]
Waiting on a follow up on the final order of these, and I'm against calling it RPC.

**Comment by salieflewis** [comment]
Do you feel like there is a logical way to break them up? They can be in whatever order we choose. Here is my suggestion.

```
NEXT_PUBLIC_PLATFORM_INDEX=''"
NEXT_PUBLIC_TOKEN_ADDRESS=''"
NEXT_PUBLIC_ALCHEMY_KEY=''"
NEXT_PUBLIC_WEB3STORAGE_TOKEN=''"
NEXT_PUBLIC_CHAIN_ID=''"
NEXT_PUBLIC_SITE_TITLE=""
NEXT_PUBLIC_APP_ID="" (Probably going to get rid of this)
NEXT_PUBLIC_SITE_DESCRIPTION="" (May be getting rid of this)
NEXT_PUBLIC_TWITTER_HANDLE=""
NEXT_PUBLIC_WEBSITE_URL=""
```
