### ISSUE TITLE
Clear up "Add to Existing" section

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible-docs#4]
see screenshot first, comments below:

<img width="788" alt="Screen Shot 2023-03-14 at 10 30 03 AM" src="https://user-images.githubusercontent.com/93691906/225033436-8b388bf0-e1e6-46d2-b8c9-9f35df359374.png">

1. Imo its unclear what is actually getting "added to existing" projects. From what I can tell we are providing info for how to add the dao-utils package to an existing project, so maybe we could make that more explicit? 

2. would be helpful to mention or at least hyperlink the dao-utils repo in that first sentence where it says "react componentry and hooks to interact"

3. @salieflewis can you confirm that we should actually be providing yarn/npm/pnpm examples as opposed to pnpm? Seems like we have moved on to pnpm being our main package manager so perhaps that could be the default example, and include a guide for installing pnpm if people havent used it before?

4. The "adding peer dependenices" part is confusing to me as related to point #1 -- because I dont think someone actually needs to do this if they are just trying to consume the dao-utils package in their own package. This specific example seems more like its trying to explain "how to manage the dao-utils monorepo and add peer dependencies to it" -- this is actually imnportant info to provide since it will help ppl make tweaks + push updates to dao-utils besides us, but there is no monorepo structure in the Flexible repo so its currently confusing as is

5. token explorer example is great !!

**Comment by Valcoholics** [comment]
The deps was written before the package go completely abstracted of all peer deps
