### ISSUE TITLE
Tutorial for Web 3 Storage API Key 

### ISSUE THREAD

**Issue by Valcoholics** [public-assembly/flexible-docs#5]

**Comment by salieflewis** [comment]
There docs for grabbing an API key are great. I think it is just fine if we link out to this [article](https://web3.storage/docs/how-tos/generate-api-token/). It just has to exist within a section that is like, how to obtain the necessary api keys... and potentially a list of prerequisites, like having a GitHub account. Check out the readme for [this repo](https://github.com/reservoirprotocol/marketplace-v2), I think they do a good job of the bare minimum for 'getting started with this repo.'

**Comment by salieflewis** [comment]
I linked the article from the web3.storage docs for this. Not sure if it is necessary to do a whole separate tutorial.
