### ISSUE TITLE
Create the custom theming parameters for the docs

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible-docs#9]
@Valcoholics moving your comment from the latest PR here.

"So the page that you wrote the about on was originally the place saver for the homepage, in terms of design we are absolutely not doing a homepage or custom theme changes?"

I feel like we should move forward with ironing out the content with just minimal changes to the theming. So if that means changing highlighted text from blue to pink, lets do that. If we get to the point where docs are feeling strong and cohesive, I think then we can think about sprucing things up.

Does that answer your question?

**Comment by Valcoholics** [comment]
so no if you look at the https://nextra.site their index page is the place holder for the sites homepage.

**Comment by salieflewis** [comment]
I see yeah, so you're hoping for a more fully designed homepage? I think with maybe an accompanying graphic, what we have so far could work for now.
